# vim: set ft=ansible
---
# Implement your Workload deployment tasks here

# Access for admin
- name: Give access to opentlc-mgr
  shell: |
         oc adm policy add-cluster-role-to-user cluster-admin opentlc-mgr

# TODO: Do we need these?
- name: Create CatalogSource Index 4.6
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - redhat-operators-index.yaml
  - community-operators-index.yaml

# Create notebook projects for user
- name: create projects for users
  include_tasks: create_project.yaml
  vars:
    t_project_name: "{{ t_user }}-notebooks"
  loop: "{{ users }}"
  loop_control:
    loop_var: t_user

- name: create guides project
  when: num_users | int > 0
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "guides"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Machine Learning Workshop Guides"

- name: install guides
  when: num_users | int > 0
  include_tasks: install-guides.yaml
  vars:
    guide: "machinelearning"

- name: install username distribution
  when: num_users | int > 0
  include_tasks: install-username-distribution.yaml

- name: search for rhsso
  k8s_facts:
    kind: DeploymentConfig
    name: rhsso
    namespace: rhsso
  register: r_rhsso_dc

- name: install rhsso
  when: r_rhsso_dc.resources | list | length == 0
  include_tasks: install-rhsso.yaml

# Setup OpenShift Serverless via operator
- name: Look for serverless subscription
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: serverless-operator
    namespace: openshift-operators
  register: r_serverless_sub

- name: show existing serverless sub
  debug:
    msg: "existing serverless sub: {{ r_serverless_sub }}"

- name: Create OpenShift Objects for Serverless (knative)
  when: r_serverless_sub.resources | list | length == 0
  include_tasks: install-serverless.yaml

# Install  AMQ Streams for all workspaces
- name: Look for amq subscription
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: amq-streams
    namespace: openshift-operators
  register: r_amq_sub

- name: show existing amq sub
  debug:
    msg: "existing amq sub: {{ r_amq_sub }}"

- name: Create OpenShift Objects for Kafka (amq streams)
  when: r_amq_sub.resources | list | length == 0
  include_tasks: install-amqstreams.yaml

# Install Open Data Hub
- name: Look for Open Data Hub subscription
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: opendatahub-operator
    namespace: openshift-operators
  register: odh_sub

- name: show existing odh sub
  debug:
    msg: "existing odh sub: {{ odh_sub }}"

- name: Install Open Data Hub
  when: odh_sub.resources | list | length == 0
  include_tasks: install-odh.yaml

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
