---
become_override: False
ocp_username: opentlc-mgr
silent: False

num_users: 5
workshop_openshift_user_name: userXX
workshop_openshift_user_password: 'openshift'
workshop_che_user_name: userXX
workshop_che_user_password: 'openshift'
workshop_openshift_admin_password: 'r3dh4t1!'
workshop_rhsso_admin_user_name: admin
workshop_rhsso_admin_password: 'r3dh4t1!'

repo_owner: msolberg
