---
apiVersion: operator.serverless.openshift.io/v1
kind: KnativeKafka
metadata:
    name: knative-kafka
    namespace: knative-eventing
spec:
    channel:
        enabled: false 
    source:
        enabled: true 
